### ISSUE TITLE
Add support for multiple OIDC providers

### ISSUE THREAD

**Issue by aaronlippold** [mitre/vulcan#664]
## Overview
Currently, Vulcan only supports configuring one OIDC provider at a time. Many organizations would benefit from offering multiple authentication options to their users, such as Google, Azure AD, OKTA, GitHub, and other OIDC-compliant providers.

## Current Limitation
- The application can only be configured with a single OIDC provider
- Users don't have a choice of authentication methods beyond the single configured provider

## Proposed Enhancement
- Allow configuration of multiple OIDC providers in `vulcan.yml`
- Update the login UI to display multiple provider buttons (similar to many modern applications)
- Each provider would have its own configuration section with client ID, secret, and discovery URL

## Benefits
- Users can choose their preferred authentication method
- Organizations can support different identity providers for different user groups
- Improved flexibility for deployment in diverse environments

## Technical Considerations
- The recent PR adding OIDC discovery support provides a good foundation for this enhancement
- Would require changes to:
  - Configuration structure in `vulcan.yml`
  - OmniAuth initialization to support multiple providers
  - Login UI to show multiple provider options
  - Session handling to track which provider was used

## Example Configuration
```yaml
oidc:
  providers:
    okta:
      enabled: true
      client_id: xxx
      client_secret: xxx
      discovery_url: https://example.okta.com/.well-known/openid-configuration
    google:
      enabled: true
      client_id: xxx
      client_secret: xxx
      discovery_url: https://accounts.google.com/.well-known/openid-configuration
    azure:
      enabled: true
      client_id: xxx
      client_secret: xxx
      discovery_url: https://login.microsoftonline.com/tenant/.well-known/openid-configuration
```

Related to the OKTA authentication fixes PR that added OIDC discovery support.
